name: Release Latest

on:
  push:
    branches:
      - master
      - staging

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.6.x'
      - name: Install Pinata CLI
        run: npm i -g pinata-upload-cli
      - name: Build project
        run: npm run build
        env:
          PUBLIC_NODE_ENV: '{{ env.PUBLIC_NODE_ENV }}'
          PUBLIC_IMAGE_ROOT: '{{ env.PUBLIC_IMAGE_ROOT }}'
          PUBLIC_WALLET_CONNECT_ID: '{{ env.PUBLIC_WALLET_CONNECT_ID }}'
          NODE_ENV: 'production'
      - name: Copy info
        run: cp package.json build/version.json
      - name: Upload build to Pinata
        env:
          NODE_ENV: 'production'
          PINATA_API_KEY: '${{ secrets.PINATA_API_KEY }}'
        run: pinata-cli -a $PINATA_API_KEY && pinata-cli -u build/
