name: Release Latest

on:
  push:
    branches:
      - master
      - staging

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.6.x'
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
      - name: Build project
        run: pnpm run build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build'
          tag: 'latest'
          allowUpdates: true
          skipIfReleaseExists: false
