name: Tag on Merge

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '22.12.x'
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn run build
        env:
          PUBLIC_NODE_ENV: 'production'
          PUBLIC_IMAGE_ROOT: 'https://gib.show'
          PUBLIC_WALLET_CONNECT_ID: '1f8a963aa1809cada8560d560360107d'
          NODE_ENV: 'production'
      - name: Copy info
        run: cp packages/frontend/package.json packages/frontend/dist/version.json
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'frontend-dist-${{github.sha}}'
          overwrite: true
          path: packages/frontend/dist/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'bridge-sdk-dist-${{github.sha}}'
          overwrite: true
          path: packages/bridge-sdk/dist/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'common-dist-${{github.sha}}'
          overwrite: true
          path: packages/common/dist/
  publish-github:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '22.12.x'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'frontend-dist-${{github.sha}}'
          path: packages/frontend/dist/
      - name: Read version from package.json
        id: get_version
        run: echo "VERSION=$(node -p 'require(`./packages/frontend/package.json`).version')" >> $GITHUB_ENV
      - name: Create tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git tag -a v$VERSION -m "Release v$VERSION"
          git push origin v$VERSION

  publish-npm-common:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '22.12.x'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'common-dist-${{github.sha}}'
          path: packages/common/dist/
      - run: cd packages/common
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-npm-bridge-sdk:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '22.12.x'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'bridge-sdk-dist-${{github.sha}}'
          path: packages/bridge-sdk/dist/
      - run: cd packages/bridge-sdk
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
