name: Tag on Merge

on:
  push:
    branches:
      - master

jobs:
  tag:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.6.x'
      - name: Build project
        run: npm run build
        env:
          PUBLIC_NODE_ENV: ${{ env.PUBLIC_NODE_ENV }}
          PUBLIC_IMAGE_ROOT: ${{ env.PUBLIC_IMAGE_ROOT }}
          PUBLIC_WALLET_CONNECT_ID: ${{ env.PUBLIC_WALLET_CONNECT_ID }}
      - name: Read version from package.json
        id: get_version
        run: echo "VERSION=$(node -p 'require(`./package.json`).version')" >> $GITHUB_ENV
      - name: Create tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git tag -a v$VERSION -m "Release v$VERSION"
          git push origin v$VERSION
