name: Tag on Merge

on:
  push:
    branches:
      - master

jobs:
  publish-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '22.12.x'
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'frontend-dist-${{github.sha}}'
          path: packages/frontend/dist/
      - name: Read version from package.json
        id: get_version
        run: echo "VERSION=$(node -p 'require(`./packages/frontend/package.json`).version')" >> $GITHUB_ENV
      - name: Create tag
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git tag -a v$VERSION -m "Release v$VERSION"
          git push origin v$VERSION

  publish-npm-common:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '22.12.x'
      - run: cd packages/common
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-npm-bridge-sdk:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: '22.12.x'
      - run: cd packages/bridge-sdk
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
